apiVersion: v1
data:
  values.yaml: |
    # metrics-server helm values used when kubelet serving certificates are self signed, e.g. Docker Kubernetes
    # or kind clusters without the metrics extra
    args:
      - --kubelet-insecure-tls
kind: ConfigMap
metadata:
  name: metrics-server-values
  namespace: kube-system
