apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-cluster-config-otel
  namespace: otel
spec:
  interval: 5m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: app-config-otel
      namespace: otel
  path: ./local-cluster/apps/config/otel
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      nameSpace: otel
      appName: otel
      # config values from apps.yaml

      observabilityGitHubServer: github.com
      observabilityGitHubOrg: pc-dae
      observabilityGitHubRepo: observability
      observabilityBranch: develop
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: otel-config
        optional: true
