apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-config-victoria-metrics
  namespace: victoria-metrics
spec:
  interval: 5m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: app-source-victoria-metrics
      namespace: victoria-metrics
  path: ./local-cluster/apps/victoria-metrics/config
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: mac-k8s-config
  postBuild:
    substitute:
      nameSpace: victoria-metrics
      appName: victoria-metrics
      # config values from apps.yaml

      observabilityGitHubServer: github.com
      observabilityGitHubOrg: pc-dae
      observabilityGitHubRepo: observability
      observabilityBranch: develop
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
